CREATE TABLE IF NOT EXISTS base_handler.handlers (
    id BIGINT PRIMARY KEY generated by default as identity,
    api_id BIGINT,
    hash character varying(255),
    phone character varying(255),
    directory_for_user_photo TEXT,
    directory_for_media TEXT,
    category character varying(255),
    count_group INT DEFAULT 0,
    name_handler character varying(255)
)