CREATE TABLE IF NOT EXISTS base_changed.user_changed (
    id bigint NOT NULL generated by default as identity,
    id_user bigint NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    username character varying(255),
    number character varying(255),
    user_photo text,
    updated_at timestamp with time zone NOT NULL,
    birthday text,
    flags text,
    flags2 text,
    about text,
    flags_full text,
    flags2_full text,
    bot_info text,
    personal_channel_id bigint,
    location_address text,
    location_lat double precision,
    location_lon double precision,
    location_radius integer,
	CONSTRAINT user_changed_pkey PRIMARY KEY (id, id_user, updated_at)
)
PARTITION BY RANGE (updated_at);

CREATE INDEX IF NOT EXISTS idx_user_changed_id_user_updated_at ON ONLY base_changed.user_changed USING btree (id_user, updated_at);

CREATE OR REPLACE FUNCTION base_changed.create_month_partition_user(target_date TIMESTAMPTZ)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE
    part_name TEXT;
    start_date TIMESTAMPTZ;
    end_date   TIMESTAMPTZ;
    hash_part_name TEXT;
BEGIN
    -- Определяем месяц
    start_date := date_trunc('month', target_date);
    end_date   := start_date + INTERVAL '1 month';

    part_name := format('user_changed_%s', to_char(start_date, 'YYYY_MM'));

    -- Проверяем, существует ли партиция
    IF NOT EXISTS (
        SELECT 1 FROM pg_class WHERE relname = part_name
    ) THEN
        RAISE NOTICE 'Creating main partition: %', part_name;

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS base_changed.%I PARTITION OF base_changed.user_changed
             FOR VALUES FROM (%L) TO (%L)
             PARTITION BY HASH (id_user)',
             part_name, start_date, end_date
        );
		
		
        -- Создаём 8 hash-партиции
        FOR i IN 0..7 LOOP
            hash_part_name := format('%s_p%s', part_name, i);

            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS base_changed.%I PARTITION OF base_changed.%I
                 FOR VALUES WITH (modulus 8, remainder %s);',
                hash_part_name, part_name, i
            );
        END LOOP;
    END IF;
END;
$$;