CREATE TABLE IF NOT EXISTS base_changed.word_group_all_changed (
    id bigint NOT NULL generated by default as identity,
    id_group bigint NOT NULL,
    info_group text,
    title_group text,
    find_group character varying(255) DEFAULT NULL::character varying,
    hash_group character varying(255) DEFAULT NULL::character varying,
    type smallint,
    date timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    linked_id bigint,
    flags text,
    flags2 text,
	CONSTRAINT word_group_all_changed_pkey PRIMARY KEY (id, id_group, date)
)
PARTITION BY RANGE (date);

CREATE INDEX IF NOT EXISTS idx_wga_changed_id_group_date ON ONLY base_changed.word_group_all_changed USING btree (id_group, date);

CREATE OR REPLACE FUNCTION base_changed.create_month_partition_group(target_date TIMESTAMPTZ)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE
    part_name TEXT;
    start_date TIMESTAMPTZ;
    end_date   TIMESTAMPTZ;
    hash_part_name TEXT;
BEGIN
    -- Определяем месяц
    start_date := date_trunc('month', target_date);
    end_date   := start_date + INTERVAL '1 month';

    part_name := format('word_group_all_changed_%s', to_char(start_date, 'YYYY_MM'));

    -- Проверяем, существует ли партиция
    IF NOT EXISTS (
        SELECT 1 FROM pg_class WHERE relname = part_name
    ) THEN
        RAISE NOTICE 'Creating main partition: %', part_name;

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS base_changed.%I PARTITION OF base_changed.word_group_all_changed
             FOR VALUES FROM (%L) TO (%L)
             PARTITION BY HASH (id_group)',
             part_name, start_date, end_date
        );
		
		
        -- Создаём 8 hash-партиции
        FOR i IN 0..7 LOOP
            hash_part_name := format('%s_p%s', part_name, i);

            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS base_changed.%I PARTITION OF base_changed.%I
                 FOR VALUES WITH (modulus 8, remainder %s);',
                hash_part_name, part_name, i
            );
        END LOOP;
    END IF;
END;
$$;