CREATE TABLE IF NOT EXISTS base_data.messages_properties (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_group    BIGINT NOT NULL,
    id_message  BIGINT NOT NULL,
    is_comments SMALLINT DEFAULT 2 NOT NULL,
    grouped_id  BIGINT,
    flags       TEXT,
	flags2      TEXT,
	has_text    BOOLEAN NOT NULL DEFAULT false,
	has_media   BOOLEAN NOT NULL DEFAULT false,
	media_type  TEXT,
	media_value jsonb,
    forwards    INTEGER,
	is_forward  BOOLEAN NOT NULL DEFAULT false,
	fwd_value   jsonb,
	views       INTEGER,
	replies     INTEGER,
	via_bot_id  BIGINT,
	via_business_bot_id  BIGINT,
	edit_date   TIMESTAMPTZ,
    date        TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    id_from     BIGINT,
    PRIMARY KEY (id, id_group, date)
) PARTITION BY RANGE (date);

CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_messages_properties ON base_data."messages_properties"
                    (id_group, id_message, is_comments, date);

CREATE OR REPLACE FUNCTION base_data.create_month_partition_properties(target_date TIMESTAMPTZ)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE
    part_name TEXT;
    start_date TIMESTAMPTZ;
    end_date   TIMESTAMPTZ;
    hash_part_name TEXT;
BEGIN
    -- Определяем месяц
    start_date := date_trunc('month', target_date);
    end_date   := start_date + INTERVAL '1 month';

    part_name := format('messages_properties_%s', to_char(start_date, 'YYYY_MM'));

    -- Проверяем, существует ли партиция
    IF NOT EXISTS (
        SELECT 1 FROM pg_class WHERE relname = part_name
    ) THEN
        RAISE NOTICE 'Creating main partition: %', part_name;

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS base_data.%I PARTITION OF base_data.messages_properties
             FOR VALUES FROM (%L) TO (%L)
             PARTITION BY HASH (id_group)',
             part_name, start_date, end_date
        );
		
		
        -- Создаём 16 hash-партиции
        FOR i IN 0..15 LOOP
            hash_part_name := format('%s_p%s', part_name, i);

            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS base_data.%I PARTITION OF base_data.%I
                 FOR VALUES WITH (modulus 16, remainder %s);',
                hash_part_name, part_name, i
            );
        END LOOP;
    END IF;
END;
$$;
