CREATE TABLE IF NOT EXISTS base_data.chat (
    id bigint generated by default as identity NOT NULL,
    id_group bigint NOT NULL,
    id_user bigint NOT NULL,
    date_joined timestamp with time zone,
    PRIMARY KEY (id, id_group)
)
PARTITION BY HASH (id_group);

CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_chat ON base_data.chat (id_group, id_user);

DO $$
BEGIN
    FOR i IN 0..63 LOOP
        EXECUTE format('
            CREATE TABLE IF NOT EXISTS base_data.chat_part_%s
            PARTITION OF base_data.chat
            FOR VALUES WITH (MODULUS 64, REMAINDER %s);
        ', i, i);
    END LOOP;
END$$;