#-----------------------------Project Setting-----------------------------
spring.application.name=prod
server.port=5002
#-----------------------------Actuator-----------------------------
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled=true
#-----------------------------Services-----------------------------
services.nodes.dbService.key=dbService
services.nodes.dbService.name=DB_SERVICE
services.nodes.TelegramApiService.key=TelegramApiService
services.nodes.TelegramApiService.name=TELEGRAM_API_SERVICE