#-----------------------------Uri services-----------------------------
api.db.url=http://dbservice:5001
api.telegram.url=http://telegramservice:5000
api.base.url=http://prod:5002
#-----------------------------Kafka default-----------------------------
spring.kafka.bootstrap-servers=kafka:29092
#Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=latest
#Listener
spring.kafka.listener.poll-timeout=15000
spring.kafka.listener.ack-mode=BATCH
#-----------------------------Kafka reactive-----------------------------
kafka.bootstrap-servers=kafka:29092
kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.auto-offset-reset=latest
#Logs_handlers
kafka.topics.logs.name=logs_handlers
kafka.topics.logs.group-id=gui-log-handlers
#Status_listeners
kafka.topics.status.name=status_listeners
kafka.topics.status.group-id=gui-status-listeners
#-----------------------------Kafka heartbeat-----------------------------
kafka.heartbeat.topic.name=service-heartbeat
kafka.heartbeat.group-id=service-heartbeat-group
timeout_heartbeat=10000
#-----------------------------kafka notifications-----------------------------
kafka.notifications.topic.name=notifications
#-----------------------------kafka gui_notifications-----------------------------
kafka.gui-notifications.topic.name=gui_notifications
kafka.gui-notifications.group-id=gui_notifications_group-id
#-----------------------------key for logs to Listener-----------------------------
key-for-logs-to-listener=-1