input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["debezium.base_data.user"]
    group_id => "debezium.base_data.user-id"
    auto_offset_reset => "latest"
    codec => json
    max_poll_records => 2000
    fetch_min_bytes => 1048576
    fetch_max_wait_ms => 500
  }
}

filter {
  if [op] == "d" {
    # для удаления берём before
    mutate {
      add_field => { "[@metadata][action]" => "delete" }
      rename => {
        "[before][id]" => "id"
      }
    }
  } else {
    # для insert/update берём after
    mutate {
      add_field => { "[@metadata][action]" => "index" }
      rename => {
        "[after][id]" => "id"
        "[source][ts_ms]" => "version"
        "[after][id_user]" => "id_user"
        "[after][updated_at]" => "updated_at"
        "[after][username]" => "username"
        "[after][number]" => "number"
        "[after][first_name]" => "first_name"
        "[after][last_name]" => "last_name"
        "[after][pg_tags]" => "pg_tags"
        "[after][is_geo]" => "is_geo"
        "[after][is_bot]" => "is_bot"
        "[after][birthday]" => "birthday"
        "[after][flags]" => "flags"
        "[after][flags2]" => "flags2"
        "[after][flags_full]" => "flags_full"
        "[after][flags2_full]" => "flags2_full"
        "[after][about]" => "about"
        "[after][bot_info]" => "bot_info"
        "[after][personal_channel_id]" => "personal_channel_id"
        "[after][location_address]" => "location_address"
        #"[after][location_lat]" => "location_lat"
        #"[after][location_lon]" => "location_lon"
        "[after][location_radius]" => "location_radius"
      }
    }
    if [after][location_lat] and [after][location_lon] {
           mutate {
             copy => {
               "[after][location_lat]" => "[location][lat]"
               "[after][location_lon]" => "[location][lon]"
             }
           }
    }
  }

  # можно удалить лишние поля
  mutate {
    remove_field => ["source", "ts_ms", "before", "event", "ts_us", "transaction", "after", "ts_ns", "op", "@timestamp", "@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "user_write"
    #user => "elastic"
    #password => "0FruBD8UmKI_AoO3Izmv"
    #ssl_enabled => true
    #ssl_certificate_authorities => "/etc/logstash/certs/elasticsearch-ca.pem"
    action => "%{[@metadata][action]}"
    document_id => "%{id}"
    retry_on_conflict => 3    
    }

stdout {codec => rubydebug}
}
