input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["logs_handlers"]
    group_id => "logs-handlers-group"
    auto_offset_reset => "latest"
    codec => json
    max_poll_records => 2000
    fetch_min_bytes => 1048576
    fetch_max_wait_ms => 500
  }
}

filter {
 # mutate {
 #   remove_field => ["timestamp"]
 # }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs_handlers_write"
    
    #user => "elastic"
    #password => "0FruBD8UmKI_AoO3Izmv"
    #ssl_enabled => true
    #ssl_certificate_authorities => "/etc/logstash/certs/elasticsearch-ca.pem"
  }

  #stdout { codec => dots }
}
