input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/postgresql.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/${JDBC_DB}"
    jdbc_user => "${JDBC_USER}"
    jdbc_password => "${JDBC_PASSWORD}"

    schedule => "*/5 * * * * *"
    use_column_value => true                      
    tracking_column => "id"
    tracking_column_type => "numeric"
    clean_run => false
    last_run_metadata_path => "/usr/share/logstash/state/messages.yml"

    statement => "
      SELECT *
      FROM base_data.messages
      WHERE id > :sql_last_value
      ORDER BY id
      LIMIT 100000
    "
  }
}

filter {
  mutate {
    remove_field => ["@timestamp", "@version", "content_media"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "messages_write"
    document_id => "%{id}"
    #user => "elastic"
    #password => "0FruBD8UmKI_AoO3Izmv"
    #ssl_enabled => true
    #ssl_certificate_authorities => "/etc/logstash/certs/elasticsearch-ca.pem"
  }

  #stdout { codec => plain }
}

