input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/drivers/postgresql.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/${JDBC_DB}"
    jdbc_user => "${JDBC_USER}"
    jdbc_password => "${JDBC_PASSWORD}"

    schedule => "*/10 * * * * *"
    use_column_value => true
    tracking_column => "id"
    tracking_column_type => "numeric"
    clean_run => false
    last_run_metadata_path => "/usr/share/logstash/state/messages_properties.yml"

    statement => "
      SELECT 
	id,
	id_group,
	id_message,
	is_comments,
	grouped_id,
        id_from,
	flags,
	flags2,
	has_text,
	has_media,
	media_type,
	media_value::text AS media_value,
	forwards,
	is_forward,
	fwd_value::text AS fwd_value,
	views,
	replies,
	via_bot_id,
	via_business_bot_id,
	edit_date,
	date,
	created_at,
	updated_at,
	to_char(date, 'YYYY-MM') as index_month
      FROM base_data.messages_properties
      WHERE id > :sql_last_value
	AND date >= NOW() - INTERVAL '2 months'
      ORDER BY id
      LIMIT 100000
    "
  }
}


filter {
 ruby {
    code => "
       gid = event.get('grouped_id')
       if gid
         event.set('identity_id', gid)
       else
         event.set('identity_id', event.get('id'))
       end
    "
 }
 mutate {
    add_field => { "[@metadata][index_month]" => "%{index_month}" }
 }
 mutate {
    remove_field => ["@timestamp", "@version", "index_month"]
 }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "messages_properties-%{[@metadata][index_month]}"
    
    document_id => "%{id}"
    #user => "elastic"
    #password => "0FruBD8UmKI_AoO3Izmv"
    #ssl_enabled => true
    #ssl_certificate_authorities => "/etc/logstash/certs/elasticsearch-ca.pem"
  }

  # на время тестирования
  #stdout { codec => plain }
}
