input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/jdbc/postgresql.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://postgres:5432/${JDBC_DB}"
    jdbc_user => "${JDBC_USER}"
    jdbc_password => "${JDBC_PASSWORD}"

    schedule => "*/5 * * * * *"
    use_column_value => true                      # использовать id как offset
    tracking_column => "id"
    tracking_column_type => "numeric"
    clean_run => false
    last_run_metadata_path => "/etc/logstash/state/user.yml"

    statement => "
      SELECT *
      FROM base_data.user
      WHERE id > :sql_last_value
      ORDER BY id
      LIMIT 100000
    "
  }
}

filter {
 ruby {
   code => "
      event.set('version', (Time.now.to_f * 1000).to_i)
   "
 } 
 if [location_lat] and [location_lon] {
           mutate {
             copy => {
               "[location_lat]" => "[location][lat]"
               "[location_lon]" => "[location][lon]"
             }
           }
        }
 mutate {
    remove_field => ["@timestamp", "@version", "user_photo", "location_lat", "location_lon"]
 }

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "user_write"
	
    document_id => "%{id}"
    #user => "elastic"
    #password => "0FruBD8UmKI_AoO3Izmv"
    #ssl_enabled => true
    #ssl_certificate_authorities => "/etc/logstash/certs/elasticsearch-ca.pem"
  }

  #stdout { codec => plain }
}
