CREATE TABLE IF NOT EXISTS base_handler.task_chats (
    id bigint PRIMARY KEY generated by default as identity,
    id_chat bigint NOT NULL,
    offset_id_new_message bigint,
    offset_id_old_message bigint,
    date_parse_user timestamp with time zone,
    date_of_last_record timestamp with time zone
);

CREATE UNIQUE INDEX idx_uniq_tc_id_chat ON base_handler.task_chats USING btree (id_chat);