CREATE TABLE IF NOT EXISTS base_group.word_group_all (
    id bigint PRIMARY KEY generated by default as identity,
    id_group bigint,
    info_group text,
    title_group text,
    find_group character varying(255) DEFAULT NULL::character varying,
    hash_group character varying(255) DEFAULT NULL::character varying,
    id_user_join bigint,
    type smallint,
    handlers_id bigint,
    last_update timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_handle timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    total_send_request integer DEFAULT 0,
    total_detect_private integer DEFAULT 0,
    linked_id bigint,
    participants_count bigint,
    created_date timestamp with time zone,
    flags text,
    flags2 text
);


CREATE INDEX IF NOT EXISTS idx_wga_hash_group ON base_group.word_group_all USING btree (hash_group);
CREATE INDEX IF NOT EXISTS idx_wga_find_group_lower ON base_group.word_group_all USING btree (lower((find_group)::text));
CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_wga_id_group ON base_group.word_group_all USING btree (id_group);