CREATE TABLE IF NOT EXISTS base_changed.participant_changed (
    id bigint NOT NULL generated by default as identity,
    id_group bigint NOT NULL,
    participants_count bigint NOT NULL,
    date timestamp with time zone NOT NULL,
	CONSTRAINT participant_changed_pkey PRIMARY KEY (id, id_group, date)
)
PARTITION BY RANGE (date);

CREATE OR REPLACE FUNCTION base_changed.create_month_partition_participant(target_date TIMESTAMPTZ)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE
    part_name TEXT;
    start_date TIMESTAMPTZ;
    end_date   TIMESTAMPTZ;
    hash_part_name TEXT;
BEGIN
    -- Определяем месяц
    start_date := date_trunc('month', target_date);
    end_date   := start_date + INTERVAL '1 month';

    part_name := format('participant_changed_%s', to_char(start_date, 'YYYY_MM'));

    -- Проверяем, существует ли партиция
    IF NOT EXISTS (
        SELECT 1 FROM pg_class WHERE relname = part_name
    ) THEN
        RAISE NOTICE 'Creating main partition: %', part_name;

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS base_changed.%I PARTITION OF base_changed.participant_changed
             FOR VALUES FROM (%L) TO (%L)
             PARTITION BY HASH (id_group)',
             part_name, start_date, end_date
        );
		
		
        -- Создаём 16 hash-партиции
        FOR i IN 0..15 LOOP
            hash_part_name := format('%s_p%s', part_name, i);

            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS base_changed.%I PARTITION OF base_changed.%I
                 FOR VALUES WITH (modulus 16, remainder %s);',
                hash_part_name, part_name, i
            );
        END LOOP;
    END IF;
END;
$$;