CREATE TABLE IF NOT EXISTS base_data."messages" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_group BIGINT NOT NULL,
    is_comments smallint not null default 2,
    reply_to_post BIGINT,
    id_message BIGINT,
    id_user BIGINT,
    id_grouped_message BIGINT,
    content_text TEXT,
    content_media TEXT,
    id_reply BIGINT,
    date TIMESTAMPTZ not null,
    PRIMARY KEY (id, id_group, date)
) PARTITION BY RANGE(date);
					
CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_messages ON base_data."messages"
                    (id_group, id_message, is_comments, date);

CREATE OR REPLACE FUNCTION base_data.create_month_partition(target_date TIMESTAMPTZ)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE
    part_name TEXT;
    start_date TIMESTAMPTZ;
    end_date   TIMESTAMPTZ;
    hash_part_name TEXT;
BEGIN
    -- Определяем месяц
    start_date := date_trunc('month', target_date);
    end_date   := start_date + INTERVAL '1 month';

    part_name := format('messages_%s', to_char(start_date, 'YYYY_MM'));

    -- Проверяем, существует ли партиция
    IF NOT EXISTS (
        SELECT 1 FROM pg_class WHERE relname = part_name
    ) THEN
        RAISE NOTICE 'Creating main partition: %', part_name;

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS base_data.%I PARTITION OF base_data.messages
             FOR VALUES FROM (%L) TO (%L)
             PARTITION BY HASH (id_group)',
             part_name, start_date, end_date
        );
		
		
        -- Создаём 16 hash-партиции
        FOR i IN 0..15 LOOP
            hash_part_name := format('%s_p%s', part_name, i);

            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS base_data.%I PARTITION OF base_data.%I
                 FOR VALUES WITH (modulus 16, remainder %s);',
                hash_part_name, part_name, i
            );
        END LOOP;
    END IF;
END;
$$;