CREATE TABLE IF NOT EXISTS base_data.reactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_group    BIGINT NOT NULL,
    id_message  BIGINT NOT NULL,
    id_user     BIGINT NOT NULL,
    reaction    TEXT   NOT NULL,
    date        TIMESTAMPTZ NOT NULL,
    
    PRIMARY KEY (id, id_group, date)
) PARTITION BY RANGE (date);

CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_reactions ON base_data."reactions"
                    (id_group, id_message, id_user, reaction, date);

CREATE OR REPLACE FUNCTION base_data.create_month_partition_reactions(target_date TIMESTAMPTZ)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE
    part_name TEXT;
    start_date TIMESTAMPTZ;
    end_date   TIMESTAMPTZ;
    hash_part_name TEXT;
BEGIN
    -- Определяем месяц
    start_date := date_trunc('month', target_date);
    end_date   := start_date + INTERVAL '1 month';

    part_name := format('reactions_%s', to_char(start_date, 'YYYY_MM'));

    -- Проверяем, существует ли партиция
    IF NOT EXISTS (
        SELECT 1 FROM pg_class WHERE relname = part_name
    ) THEN
        RAISE NOTICE 'Creating main partition: %', part_name;

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS base_data.%I PARTITION OF base_data.reactions
             FOR VALUES FROM (%L) TO (%L)
             PARTITION BY HASH (id_group)',
             part_name, start_date, end_date
        );
		
		
        -- Создаём 8 hash-партиции
        FOR i IN 0..7 LOOP
            hash_part_name := format('%s_p%s', part_name, i);

            EXECUTE format(
                'CREATE TABLE IF NOT EXISTS base_data.%I PARTITION OF base_data.%I
                 FOR VALUES WITH (modulus 8, remainder %s);',
                hash_part_name, part_name, i
            );
        END LOOP;
    END IF;
END;
$$;