CREATE TABLE IF NOT EXISTS base_data."user" (
    id bigint PRIMARY KEY generated by default as identity,
    id_user bigint NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    username character varying(255),
    number character varying(255),
    user_photo text,
    pg_tags text,
    is_geo boolean,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    birthday text,
    flags text,
    flags2 text,
    about text,
    flags_full text,
    flags2_full text,
    is_bot boolean DEFAULT false,
    bot_info text,
    personal_channel_id bigint,
    location_address text,
    location_lat double precision,
    location_lon double precision,
    location_radius integer
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_user ON base_data.user (id_user);