CREATE TABLE IF NOT EXISTS base_data.admin_chats (
    id bigint NOT NULL generated by default as identity,
    id_group bigint NOT NULL,
    id_user bigint NOT NULL,
    status text,
    PRIMARY KEY(id, id_group)
)
PARTITION BY HASH (id_group);

CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_admin_chats ON base_data.admin_chats (id_group, id_user);

DO $$
BEGIN
    FOR i IN 0..63 LOOP
        EXECUTE format('
            CREATE TABLE IF NOT EXISTS base_data.admin_chats_part_%s
            PARTITION OF base_data.admin_chats
            FOR VALUES WITH (MODULUS 64, REMAINDER %s);
        ', i, i);
    END LOOP;
END$$;