CREATE TABLE IF NOT EXISTS base_data.gifts (
    id bigint NOT NULL generated by default as identity,
    id_group bigint NOT NULL,
    id_from bigint NOT NULL,
    id_gift character varying(255),
    message text,
    title_gift text,
    stars bigint,
    convert_stars bigint,
    date timestamp with time zone,
    flags text,
    flags2 text,
    availability_total integer,
    PRIMARY KEY(id, id_group)
)
PARTITION BY HASH (id_group);

CREATE UNIQUE INDEX IF NOT EXISTS idx_uniq_gifts ON base_data.gifts (id_group, id_from, id_gift, date) NULLS NOT DISTINCT;

DO $$
BEGIN
    FOR i IN 0..63 LOOP
        EXECUTE format('
            CREATE TABLE IF NOT EXISTS base_data.gifts_part_%s
            PARTITION OF base_data.gifts
            FOR VALUES WITH (MODULUS 64, REMAINDER %s);
        ', i, i);
    END LOOP;
END$$;