#-----------------------------Project Setting-----------------------------
spring.application.name=dbService
server.port=5001
spring.profiles.active=local
debug=true
#-----------------------------Actuator-----------------------------
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled=true
#-----------------------------FlyWay-----------------------------
spring.flyway.enabled=false
spring.flyway.default-schema=flyway
spring.flyway.locations=classpath:db/migration
#logging.level.org.flywaydb=DEBUG