#-----------------------------JDBC-----------------------------
spring.datasource.jdbc-url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.datasource.maximum-pool-size=50
#-----------------------------R2DBC-----------------------------
r2dbc.host=postgres
r2dbc.port=5432
r2dbc.db_name=${POSTGRES_DB}
r2dbc.driver=postgresql
r2dbc.username=${POSTGRES_USER}
r2dbc.password=${POSTGRES_PASSWORD}
#logging.level.io.r2dbc.postgresql=DEBUG
#logging.level.io.r2dbc.spi=DEBUG
#-----------------------------ES-----------------------------
es.enabled=true
spring.elasticsearch.uris=http://elasticsearch:9200
#spring.elasticsearch.username=elastic
#spring.elasticsearch.password=0FruBD8UmKI_AoO3Izmv
#spring.elasticsearch.ssl.verification-mode=certificate
#spring.elasticsearch.ssl.certificate-authorities=file:/config/certs/es-node1.pem
#-----------------------------Kafka default-----------------------------
kafka.enabled=true
spring.kafka.bootstrap-servers=kafka:29092
#Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=latest
#Listener
spring.kafka.listener.poll-timeout=15000
spring.kafka.listener.ack-mode=BATCH
#-----------------------------kafka heartbeat-----------------------------
kafka.heartbeat.topic.name=service-heartbeat
#-----------------------------kafka notifications-----------------------------
kafka.notifications.listener.topic.name=notifications
kafka.notifications.listener.topic.group-id=notifications_group-id
kafka.notifications.send.topic.name=gui_notifications
#-----------------------------Kafka-to-db-----------------------------
#Delay
kafka-to-db.delay-user-update-days=3
#Default
kafka-to-db.kafka.bootstrap-servers=kafka:29092
kafka-to-db.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka-to-db.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka-to-db.kafka.consumer.auto-offset-reset=latest
kafka-to-db.kafka.consumer.fetch-max-bytes=5000000
kafka-to-db.kafka.consumer.max-partition-fetch-bytes=5000000
kafka-to-db.kafka.consumer.fetch-min-bytes=3000000
kafka-to-db.kafka.consumer.fetch-max-wait-ms=2000
kafka-to-db.kafka.consumer.max-poll-records=100
kafka-to-db.kafka.listener.poll-timeout=30000
#Topic for logs
kafka-to-db.topic-for-logs=logs_handlers
kafka-to-db.key-for-logs=-1
#Topic for status
kafka-to-db.topic-for-status=status_listeners
#User
kafka-to-db.user-topic=user
kafka-to-db.user-group-id=user_listen_group_1
kafka-to-db.user-size=50
#Chat
kafka-to-db.chat-topic=chat
kafka-to-db.chat-group-id=chat_listen_group_1
kafka-to-db.chat-size=50
#AdminChats
kafka-to-db.admin-chats-topic=admin_chats
kafka-to-db.admin-chats-group-id=admin_chats_listen_group_1
kafka-to-db.admin-chats-size=50
#Reactions
kafka-to-db.reactions-topic=reactions
kafka-to-db.reactions-group-id=reactions_listen_group_1
kafka-to-db.reactions-size=50
#ReactionsGeneral
kafka-to-db.reactions-general-topic=reactions_general
kafka-to-db.reactions-general-group-id=reactions_general_listen_group_1
kafka-to-db.reactions-general-size=50
#Gifts
kafka-to-db.gifts-topic=gifts
kafka-to-db.gifts-group-id=gifts_listen_group_1
kafka-to-db.gifts-size=50
#Messages
kafka-to-db.messages-topic=messages
kafka-to-db.messages-group-id=messages_listen_group_1
kafka-to-db.messages-size=50
#MessagesEntities
kafka-to-db.messages-entities-topic=messages_entities
kafka-to-db.messages-entities-group-id=messages_entities_listen_group_1
kafka-to-db.messages-entities-size=50
#MessagesProperties
kafka-to-db.messages-properties-topic=messages_properties
kafka-to-db.messages-properties-group-id=messages_properties_listen_group_1
kafka-to-db.messages-properties-size=50
#TaskChats
kafka-to-db.task-chats-topic=task_chats
kafka-to-db.task-chats-group-id=task-chats_listen_group_1
kafka-to-db.task-chats-size=1
#WordGroupAll
kafka-to-db.word-group-all-topic=word_group_all
kafka-to-db.word_group_all-group-id=word_group_all_listen_group_1
kafka-to-db.word-group-all-size=1