[global]
repo1-path=/var/lib/pg_back
repo1-retention-full=1
repo1-retention-diff=3
repo1-retention-archive=2
repo1-block=y
repo1-bundle=n
log-level-console=info
start-fast=y
process-max=4

[global:archive-push]
compress-level=3

[main]
pg1-path=/var/lib/postgresql/data

