scrape_configs:
  - job_name: 'dbservice_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['dbservice:5001']
      
  - job_name: 'prod_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['prod:5002']
      
  - job_name: 'reactor_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reactor:5003']