#-----------------------------Project Setting-----------------------------
spring.application.name=reactor
server.port=5003
spring.profiles.active=local
spring.jackson.property-naming-strategy=SNAKE_CASE
#-----------------------------Actuator-----------------------------
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled=true
