#-----------------------------Uri services-----------------------------
api.db.url=http://dbservice:5001
#-----------------------------R2DBC-----------------------------
r2dbc.driver=postgresql
r2dbc.host=postgres
r2dbc.port=5432
r2dbc.user=${POSTGRES_USER}
r2dbc.password=${POSTGRES_PASSWORD}
r2dbc.database=${POSTGRES_DB}
#-----------------------------ES-----------------------------
spring.elasticsearch.uris=elasticsearch:9200
spring.elasticsearch.https=false
#spring.elasticsearch.cert=file:/config/certs/elasticsearch-ca.pem
#spring.elasticsearch.username=elastic
#spring.elasticsearch.password=0FruBD8UmKI_AoO3Izmv